-- Run this once in a Snowflake worksheet as ACCOUNTADMIN.
-- Dagster then calls this procedure after every successful Snowflake RAW load.

USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DB;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE PROCEDURE ANALYTICS.REFRESH_FRAUD_GOLD()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN

    CREATE OR REPLACE TABLE ANALYTICS.FRAUD_DAILY_SUMMARY AS
    SELECT
        TO_DATE(TRANSACTION_TIMESTAMP) AS TRANSACTION_DATE,
        COUNT(*) AS TRANSACTION_COUNT,
        SUM(AMOUNT) AS TRANSACTION_AMOUNT,
        AVG(AMOUNT) AS AVERAGE_TRANSACTION_AMOUNT,
        MIN(AMOUNT) AS MINIMUM_TRANSACTION_AMOUNT,
        MAX(AMOUNT) AS MAXIMUM_TRANSACTION_AMOUNT,
        COUNT_IF(FRAUD_LABEL = 'Fraud') AS HISTORICAL_FRAUD_COUNT,
        COUNT_IF(FRAUD_LABEL = 'Legitimate') AS HISTORICAL_LEGITIMATE_COUNT,
        ROUND(100.0 * COUNT_IF(FRAUD_LABEL = 'Fraud') / NULLIF(COUNT(*), 0), 2)
            AS HISTORICAL_FRAUD_PERCENTAGE,
        COUNT_IF(REVIEW_PRIORITY = 'High') AS HIGH_REVIEW_PRIORITY_COUNT,
        COUNT_IF(REVIEW_PRIORITY = 'Medium') AS MEDIUM_REVIEW_PRIORITY_COUNT,
        COUNT_IF(REVIEW_PRIORITY = 'Low') AS LOW_REVIEW_PRIORITY_COUNT,
        COUNT_IF(RAPID_REPEAT_FLAG = TRUE) AS RAPID_REPEAT_COUNT
    FROM RAW.TRANSACTIONS
    GROUP BY TO_DATE(TRANSACTION_TIMESTAMP);

    CREATE OR REPLACE TABLE ANALYTICS.AMOUNT_BUCKET_SUMMARY AS
    SELECT
        AMOUNT_BUCKET AS AMOUNT_RANGE,
        COUNT(*) AS TRANSACTION_COUNT,
        SUM(AMOUNT) AS TRANSACTION_AMOUNT,
        AVG(AMOUNT) AS AVERAGE_TRANSACTION_AMOUNT,
        COUNT_IF(FRAUD_LABEL = 'Fraud') AS HISTORICAL_FRAUD_COUNT,
        COUNT_IF(REVIEW_PRIORITY = 'High') AS HIGH_REVIEW_PRIORITY_COUNT,
        COUNT_IF(REVIEW_PRIORITY = 'Medium') AS MEDIUM_REVIEW_PRIORITY_COUNT,
        COUNT_IF(REVIEW_PRIORITY = 'Low') AS LOW_REVIEW_PRIORITY_COUNT,
        COUNT_IF(RAPID_REPEAT_FLAG = TRUE) AS RAPID_REPEAT_COUNT
    FROM RAW.TRANSACTIONS
    GROUP BY AMOUNT_BUCKET;

    CREATE OR REPLACE TABLE ANALYTICS.RISK_TIME_DASHBOARD AS
    SELECT
        TIME_OF_DAY AS TIME_SEGMENT,
        TIME_BAND AS TIME_WINDOW,
        AMOUNT_BUCKET AS AMOUNT_RANGE,
        REVIEW_PRIORITY,
        COUNT(*) AS TRANSACTION_COUNT,
        SUM(AMOUNT) AS TRANSACTION_AMOUNT,
        AVG(AMOUNT) AS AVERAGE_TRANSACTION_AMOUNT,
        COUNT_IF(RAPID_REPEAT_FLAG = TRUE) AS RAPID_REPEAT_COUNT,
        COUNT_IF(REPEATED_ANONYMIZED_PATTERN_FLAG = TRUE) AS REPEATED_PATTERN_COUNT,
        COUNT_IF(FRAUD_LABEL = 'Fraud') AS HISTORICAL_FRAUD_COUNT,
        AVG(AMOUNT_Z_SCORE) AS AVERAGE_AMOUNT_Z_SCORE,
        AVG(AMOUNT_PERCENTILE) AS AVERAGE_AMOUNT_PERCENTILE
    FROM RAW.TRANSACTIONS
    GROUP BY TIME_OF_DAY, TIME_BAND, AMOUNT_BUCKET, REVIEW_PRIORITY;

    CREATE OR REPLACE VIEW ANALYTICS.ANALYST_REVIEW_QUEUE AS
    SELECT
        TRANSACTION_ID AS REVIEW_TRANSACTION_ID,
        TRANSACTION_TIMESTAMP AS TRANSACTION_TIME,
        AMOUNT AS TRANSACTION_AMOUNT,
        AMOUNT_BUCKET AS AMOUNT_RANGE,
        TIME_OF_DAY AS TIME_SEGMENT,
        TIME_BAND AS TIME_WINDOW,
        RAPID_REPEAT_FLAG AS RAPID_REPEAT_INDICATOR,
        REPEATED_ANONYMIZED_PATTERN_FLAG AS REPEATED_PATTERN_INDICATOR,
        AMOUNT_OUTLIER_FLAG AS AMOUNT_OUTLIER_INDICATOR,
        AMOUNT_Z_SCORE AS AMOUNT_DEVIATION_SCORE,
        AMOUNT_PERCENTILE AS AMOUNT_PERCENTILE_RANK,
        REVIEW_SCORE,
        REVIEW_PRIORITY,
        RISK_REASON AS REVIEW_REASON
    FROM RAW.TRANSACTIONS;

    RETURN 'Gold refresh completed successfully.';
END;
$$;
