USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DB;

SELECT COUNT(*) AS RAW_TRANSACTION_COUNT
FROM RAW.TRANSACTIONS;

SELECT COUNT(*) AS GOLD_DAILY_ROWS
FROM ANALYTICS.FRAUD_DAILY_SUMMARY;

SELECT COUNT(*) AS GOLD_QUEUE_ROWS
FROM ANALYTICS.ANALYST_REVIEW_QUEUE;

SELECT *
FROM ANALYTICS.ANALYST_REVIEW_QUEUE
ORDER BY
    CASE REVIEW_PRIORITY
        WHEN 'High' THEN 1
        WHEN 'Medium' THEN 2
        WHEN 'Low' THEN 3
        ELSE 4
    END,
    RAPID_REPEAT_INDICATOR DESC,
    AMOUNT_PERCENTILE_RANK DESC,
    TRANSACTION_TIME DESC
LIMIT 20;
