-- Silver layer validation notebook (Databricks SQL)
-- Set the three widgets before running:
--   catalog_name = workspace
--   batch_id = the batch generated by Dagster, for example s3_<etag-prefix>
--   source_file_name = the file processed in this batch

-- 1. Confirm the batch completed successfully in the Silver audit log.
SELECT
    source_file_name,
    batch_id,
    status,
    bronze_row_count,
    silver_row_count,
    bronze_row_count - silver_row_count AS rows_removed_in_silver,
    started_ts,
    completed_ts,
    error_message
FROM IDENTIFIER(:catalog_name || '.ops.silver_processed_batches')
WHERE batch_id = :batch_id
  AND source_file_name = :source_file_name
ORDER BY started_ts DESC;

-- 2. Reconcile the Silver batch row count against the latest successful audit record.
WITH audit AS (
    SELECT silver_row_count
    FROM IDENTIFIER(:catalog_name || '.ops.silver_processed_batches')
    WHERE batch_id = :batch_id
      AND source_file_name = :source_file_name
      AND status = 'SUCCESS'
    ORDER BY completed_ts DESC
    LIMIT 1
), silver AS (
    SELECT COUNT(*) AS actual_silver_row_count
    FROM IDENTIFIER(:catalog_name || '.silver.transactions_silver_incremental')
    WHERE batch_id = :batch_id
      AND source_file = :source_file_name
)
SELECT
    audit.silver_row_count AS audit_silver_row_count,
    silver.actual_silver_row_count,
    CASE WHEN audit.silver_row_count = silver.actual_silver_row_count
         THEN 'PASS' ELSE 'FAIL' END AS reconciliation_result
FROM audit CROSS JOIN silver;

-- 3. Required-field and domain checks for the selected Silver batch.
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN transaction_id IS NULL THEN 1 ELSE 0 END) AS null_transaction_id_count,
    SUM(CASE WHEN transaction_timestamp IS NULL THEN 1 ELSE 0 END) AS null_transaction_timestamp_count,
    SUM(CASE WHEN amount IS NULL THEN 1 ELSE 0 END) AS null_amount_count,
    SUM(CASE WHEN amount < 0 THEN 1 ELSE 0 END) AS negative_amount_count,
    SUM(CASE WHEN fraud_label NOT IN ('Fraud', 'Legitimate') OR fraud_label IS NULL
             THEN 1 ELSE 0 END) AS invalid_fraud_label_count,
    SUM(CASE WHEN suspicious_transaction_risk NOT IN ('High', 'Medium', 'Low')
                  OR suspicious_transaction_risk IS NULL
             THEN 1 ELSE 0 END) AS invalid_review_priority_count
FROM IDENTIFIER(:catalog_name || '.silver.transactions_silver_incremental')
WHERE batch_id = :batch_id
  AND source_file = :source_file_name;

-- 4. Confirm Silver has no exact duplicate transaction rows after standardisation.
-- Audit metadata is deliberately excluded: it is different for each ingestion run.
SELECT
    transaction_id,
    COUNT(*) AS duplicate_row_count
FROM IDENTIFIER(:catalog_name || '.silver.transactions_silver_incremental')
WHERE batch_id = :batch_id
  AND source_file = :source_file_name
GROUP BY transaction_id
HAVING COUNT(*) > 1
ORDER BY duplicate_row_count DESC;

-- 5. Show risk-priority and fraud-label distribution for demo evidence.
SELECT
    suspicious_transaction_risk AS review_priority,
    fraud_label AS historical_label,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount), 2) AS transaction_amount
FROM IDENTIFIER(:catalog_name || '.silver.transactions_silver_incremental')
WHERE batch_id = :batch_id
  AND source_file = :source_file_name
GROUP BY suspicious_transaction_risk, fraud_label
ORDER BY
    CASE suspicious_transaction_risk
        WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 WHEN 'Low' THEN 3 ELSE 4
    END,
    fraud_label;

-- 6. Show the top 100 analyst-review candidates from the selected batch.
SELECT
    transaction_id,
    transaction_timestamp,
    amount,
    amount_bucket,
    time_of_day,
    time_band,
    rapid_repeat_flag,
    repeated_anonymized_pattern_flag,
    amount_outlier_flag,
    suspicious_transaction_risk
FROM IDENTIFIER(:catalog_name || '.silver.transactions_silver_incremental')
WHERE batch_id = :batch_id
  AND source_file = :source_file_name
ORDER BY
    CASE suspicious_transaction_risk
        WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 WHEN 'Low' THEN 3 ELSE 4
    END,
    rapid_repeat_flag DESC,
    amount DESC,
    transaction_timestamp DESC
LIMIT 100;
